spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/company
spring.datasource.username=root
spring.datasource.password=mynameis16
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
